name: master_ci

on:
  pull_request:
  push:
    branches:
      - master


jobs:
  build:
    name: "java 16 build"
    runs-on: [self-hosted]
    steps:
      - name: check out
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0  # was 1 and changed to 0 as sonar complain shallow fetch - Warning:  Shallow clone detected, no blame information will be provided. You can convert to non-shallow with 'git fetch --unshallow'.
      - name: setup java 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          overwrite-settings: false
      - name: setup maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.1
#      - name: cache maven artifacts
#        uses: actions/cache@v2.1.6
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
#          restore-keys: ${{ runner.os }}-maven-
      - name: verify and check updates
        run: |
          mvn jacoco:prepare-agent clean test jacoco:report sonar:sonar site site-deploy deploy
          mvn versions:display-dependency-updates
      - id: projectVersionAsImageTag
        run: |
          MAVEN_PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "::set-output name=IMAGE_TAG::${MAVEN_PROJECT_VERSION}-$(git rev-parse --short=8 HEAD)"
          echo "${MAVEN_PROJECT_VERSION}"
          echo "${{ steps.projectVersionAsImageTag.outputs }}"
          echo "Image version will be ${{ steps.projectVersionAsImageTag.outputs.IMAGE_TAG }}"
        shell: bash
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2.7.0
        with:
          report_paths: '**/surefire-reports/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_failure: true